#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Illuminate\Container\Container;
use Illuminate\Database\Capsule\Manager as EloquentCapsule;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;

$container = new Container;
$events = new Dispatcher($container);

$capsule = new EloquentCapsule();

$container->bind(\Illuminate\Database\ConnectionResolverInterface::class, fn() => $capsule);
$container->bind(\Illuminate\Database\ConnectionResolverInterface::class, fn() => $capsule);
$container->bind(\Illuminate\Database\Migrations\MigrationRepositoryInterface::class, \Illuminate\Database\Migrations\DatabaseMigrationRepository::class);

$artisan = new Application($container, $events, 'Version 1');
$artisan->setName('My Console App Name');

$commands = require_once __DIR__ . '/app/commands.php';

foreach ($commands as $command) {
    $artisan->resolve($command);
}

$artisan->run();
