FROM laravelphp/vapor:php81

LABEL maintainer="Antoine Benevaut <me@abenevaut.dev>"

RUN pecl channel-update pecl.php.net \
    && pecl install yaf \
    && rm -rf /tmp/pear

RUN docker-php-ext-enable yaf

COPY runtime/docker-php-ext-yaf.ini.production /usr/local/etc/php/conf.d/docker-php-ext-yaf.ini
