<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?= $content ?></title>
    <link rel="stylesheet" href="https://unpkg.com/teutonic-css@0.7.13/teutonic.min.css">
</head>
<body class="flex column min-height-full">

<header class="flex wrap-no gap_xs ma-t_m">
    <div class="span-auto">
        <a href="/" class="pa_s pa-l_l block bo-t_px bo-r_px bo-b_px text-bold docs-teutonic-link active">
            Yafarel
        </a>
    </div>
<!--    <div class="span-auto ma-l-auto">-->
<!--        <a href="/auth/login" class="button prime ma-r_l">Login</a>-->
<!--    </div>-->
</header>

<div class="span-auto">
    <!-- MS Edge:  ↓  pa_l doesm't work for some stange reason -->
    <nav class="pa-h_l pa-v_m flex gap_s">
        <div>
            <h3 class="text_l bo-b_xs pa-b_xs">Navigation</h3>
            <ul class="columns cols-6 cols-4-t cols-2-p">

                <li>
                    <a href="/auth/login" class="block-link pa_xs">Login</a>
                </li>

                <li>
                    <a href="/auth/register" class="block-link pa_xs">Register</a>
                </li>

                <li>
                    <a href="/auth/forgotten-password" class="block-link pa_xs">Forgot password</a>
                </li>

            </ul>
        </div>
    </nav>
</div>

<div class="pa-h_l">

    <form class="gap-no read_s">
        <div class="form-box pa_m">
            <label for="email" class="mini-label">E-mail</label>
            <input type="email" id="email" name="email" class="input text_l pa_m ra-t_s" placeholder="your@email.com" required="required">
        </div>
        <div class="form-box pa_m">
            <label for="password" class="mini-label">Password</label>
            <input type="password" id="password" name="password" class="input text_l pa_m" placeholder="•••••••••" required="required">
        </div>
        <button class="button block prime text_l pa_m ra-b_s bo-b_xs" type="submit">Log in &rarr;</button>
        <div class="text_s ma-t_m flex pa-h_m">
            <div>
                <input type="checkbox" id="choice" name="choice" class="checkbox">
                <label for="choice">Remember me</label>
            </div>
        </div>
    </form>

</div>

<footer class="pa-h_l pa-v_m text_s span-auto">
    <nav class="flex">
        <div>
            <b>Yafarel</b> v0.0.0<br>
            by <a href="https://github.com/abenevaut" class="link">Antoine Benevaut</a><br>
        </div>
        <div class="ma-l-auto span-auto flex-end">
            <a class="text-bold link" href="https://github.com/abenevaut/yafarel">GitHub ›</a>
        </div>
    </nav>
</footer>

</body>
</html>
<!-- You have reached the end of the internet  -->